# Generated by Django 6.0.4 on 2026-04-11 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Album Title')),
                ('artist', models.CharField(max_length=200, verbose_name='Album Artist')),
                ('released', models.IntegerField(default=1970, verbose_name='Album Released')),
                ('is_published', models.BooleanField(default=True, verbose_name='Album Published')),
            ],
            options={
                'verbose_name': 'Album',
                'verbose_name_plural': 'Albums',
                'ordering': ['-released'],
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Song Title')),
                ('duration', models.IntegerField(default=0, verbose_name='Song Duration')),
                ('track', models.CharField(max_length=200, verbose_name='Song Track Number on album')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='api.album', verbose_name='Song Album')),
            ],
            options={
                'verbose_name': 'Song',
                'verbose_name_plural': 'Songs',
            },
        ),
    ]
